### PR TITLE
fix: signup button border hover effect

### LINKED ISSUE #1089: 🐞Bug:  Change in position of navbar elements
### Description

In the navbar when you hover over the signup button you will observer a slight positioning change in the navbar links like home , clubs and other elements. This is affecting the UI experience. Also we instead of adding a border when we hover over the solid color background button we can change the opacity of the color to highlight the active state.

### Screenshots

_No response_

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

### PR DESCRIPTION
**Pull request by dhananjay-Byte**
closes #1089 

### 👷🏻 Changes made  

Fixed the signup button border hover effect by changing the border pixel property.
border: #e26959 solid 2px;  - >   border: #e26959 solid 1px;

### 📸 Screenshots 
 
Before Changes:
demo-gif

After Changes:
ezgif com-video-to-gif

### CODE REVIEW

**Comment by dhananjay-Byte** [comment]
@tamalCodes it is a global change. This hover effect fix will be reflected in all the pages where Button component is used and auth page is one of them.

**Comment by dhananjay-Byte** [comment]
also it would be nice if we can use another approach to highlight active or hover effect button more distinction. for example we  can add other other with low opacity or we can change the border from solid to dotted or other.

**Comment by tamalCodes** [comment]
Hi @ dhananjay-Byte, for now, the hover effect we have is good enough. We are aimed at keeping the site clean and minimal as possible.

**Review by tamalCodes — APPROVED** [review]
# Amazing work 🎉
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/MilanCommunity/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
