### PR TITLE
fix: done the working of the issue of footer responsiveness and hero section also

### PR DESCRIPTION
**Pull request by RAHUL956777**
image
image

### CODE REVIEW

**Comment by tamalCodes** [comment]
Hi @RAHUL956777 , do let me know when this PR is ready to be merged. Because I don't see any changes.

**Comment by RAHUL956777** [comment]
the footer section have some issue because of the other-sections big image and the alignment...i am align it and fixed those sections . after that footer is responsive automatically ...

**Comment by RAHUL956777** [comment]
yes task is done now the page is responsive ...and footer section is also

**Comment by tamalCodes** [comment]
Hi @RAHUL956777 , the changes you have done do not make any sense at all. Nor are they visible to me. As you can see in the screenshot comparison below (the Left is yours the right is the deployed ones) there is barely any change at all. Plus in the last screenshot, you will notice how your changes are in fact breaking more responsiveness.

As I said this is taking too much time, so I will be closing this PR and the issue and working on it myself ASAP. This issue is of very high priority and it already has been a week. 


Screenshot_2
Screenshot_1
Screenshot_3
Screenshot_4

**Comment by RAHUL956777** [comment]
**without my code**

image
**with my code**
image

**Pull request closed without merging**
