### PR TITLE
feat: lazy loading added to pages

### PR DESCRIPTION
**Pull request by Avinash905**
### Related Issue 

Closes: #853 

#### Changes made 👷🏻‍♂️

- Imported all the pages using react lazy
- Added react suspense to the routes
- Improved the loading spinner css to be shown at the center of the page

### CODE REVIEW

**Review by tamalCodes — COMMENTED** [review]
Hi @Avinash905 , i saw your changes - they look amazing.

However, there's a slight problem from the design perspective. When you try to load a page, that has not been previously loaded - we have an empty page with a loader, and then the page loads in. This , even for the slightest while is a very bad UX as you get a super empty page.

Can this issue be somehow handled ?


image

**Comment by Avinash905** [comment]
@tamalCodes I have made some changes. Now the navbar will appear while loading.

**Comment by tamalCodes** [comment]
> @tamalCodes I have made some changes. Now the navbar will appear while loading.

That is really cool addition, however, I would like something else. It is not about having a navbar, it is more about having a skeleton or a pre-defined structure that lets the user know that okay, the contents are loading in. 

With looks like this, it will make the UX much better than having a simple spinner. The goal is to make our project much more UX-friendly and impressive !


image

**Comment by tamalCodes** [comment]
### Updates 🚧

Hi there, because of some personal and professional reasons we had to change our code structure, and UI. The changes are visible in [this pull request](https://github.com/tamalCodes/Milan/pull/994), and will be merged as soon as they are done. Until then we need to halt all the progress (merging PRs). 

There might be a few conflicts in this PR, we will work on those too.
We are also moving to a new domain : https://milanhub.org

Sorry for the inconveniences caused.
Team Milan.

**Pull request closed without merging**
