### PR TITLE
fix: in medium screen x-axis scrollable fixed

### PR DESCRIPTION
**Pull request by Ayushpanditmoto**
Fixed: medium Screen X-Axis Scrolling Issue (#1121)

## Before:
In medium mode, the X-axis was scrollable, causing usability issues.

## After Fix:
I have resolved this issue, and now the X-axis remains fixed in tablet mode.

## Here is a demo

https://github.com/MilanCommunity/Milan/assets/31253617/f6e25e65-6d2e-42f9-b329-fa5bda0a1922

### CODE REVIEW

**Comment by tamalCodes** [comment]
Hi @Ayushpanditmoto , i dug deep into why the horizontal scroll was an issue in the first place. Looks like the website is not responsive in certain areas. So instead of `overflow-x: hidden`  (which is a solution, but a kind of naive approach)  - I think it would be better if we could fix these responsiveness issues. That would be a better solution.

image

As an example in this image, we can fix the overflow issue by fixing the way the elements are present. Instead of a horizontal manner, they can be kept vertically to reduce the flow.

**Comment by Ayushpanditmoto** [comment]
Yep working on this issues

**Comment by Ayushpanditmoto** [comment]
@tamalCodes code is poorly written can i replace it with styled components i will make it responsive only that part which is effecting

**Comment by tamalCodes** [comment]
> @tamalCodes code is poorly written can i replace it with styled components i will make it responsive only that part which is effecting

Hi we are using twitter Bootstrap which is user friendly in the most part - I'd recommend closing this issue if you are unable to do it as of now. We need this to be fixed very soon so I'll take it over.

**Pull request closed without merging**
