### PR TITLE
feat: improve clubs page accessibility

### LINKED ISSUE #1105: Feature: Make /clubs more accessible
### Description

The [clubs' page](https://milanhub.org/clubs) lacks some accessibility as shown in the screenshots cause of the wrong use of elements. Using the right elements will greatly improve its accessibility.

### Screenshots

Screenshot 2023-10-01 at 21 38 28

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
closes #1105 

### 👷🏻 Changes made  

Use right elements to improve accessibility.

### CODE REVIEW

**Comment by Olaleye-Blessing** [comment]
@tamalCodes Could you look at this?

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Hi there, looks like something is causing a gap which is making the content off-center. Please take a look at [this](https://www.loom.com/share/d23f9cb51520461384315bd9f177aabd?sid=72f690b0-c9df-4d79-b034-d30d51cd1246) recording.

**Comment by Olaleye-Blessing** [comment]
> Hi there, looks like something is causing a gap which is making the content off-center. Please take a look at [this](https://www.loom.com/share/d23f9cb51520461384315bd9f177aabd?sid=72f690b0-c9df-4d79-b034-d30d51cd1246) recording.

Just noticed this. It happened cause of the default styling of `ul` element.

**Comment by Olaleye-Blessing** [comment]
You can check it now.

**Review by tamalCodes — APPROVED** [review]
# Amazing work 🎉
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/MilanCommunity/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
